### ISSUE TITLE
Could not connect to database

### ISSUE THREAD

**Issue by metamorphious** [setiseta/observium#2]
Thanks for providing this docker container. Unfortunately I can't get it to connect to my database. I'm trying to use it with another container that contains a MariaDB. This is the docker-compose file I use:

```
version: '3'
services:
  observium:
    image: seti/observium:latest
    restart: always
    links:
      - mariadb:mysql
    ports:
      - "8080:80"
    environment:
      POLLER: 24
      TZ: Europe/Berlin
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: observium
      DB_USER: observium
      DB_PASS: xxx
    volumes:
      - data:/data

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: observium
      MYSQL_USER: observium
      MYSQL_PASSWORD: xxx
      TERM: xterm
    volumes:
      - database:/var/lib/mysql
      - ./data/db-config/:/etc/mysql/conf.d
     command: mysqld --skip-name-resolve

volumes:
  data:
  database:
```

But when I start up the container I get the following error message:
```
observium_1  | *** Running /etc/my_init.d/init.sh...
observium_1  | ln: failed to create symbolic link ‘/opt/observium/config.php’: File exists
observium_1  | ln: failed to create symbolic link ‘/opt/observium/rrd/rrd’: File exists
observium_1  | Waiting for database server to accept connections...........................................................
observium_1  | Could not connect to database server. Aborting...
observium_1  | *** /etc/my_init.d/init.sh failed with status 1
```

Do you have an idea where the problem is?
